#!/bin/bash

# Define the IP address range
target="192.168.178.20:8080"

# Loop through the IP address range
#for ip in $(seq $ip_range); do
  # Try to curl the IP address
  curl -s http://$target > /dev/null 2>&1

  # Check if the curl request was successful
  if [ $? -eq 0 ]; then
    echo "IP address $target is reachable."
  else
    echo "IP address $target is not reachable."
  fi
#done
